export default [
    {
        id: 1990,
        name: "9 in 1 Foldable Knife Multifunctional Pliers",
        slug: "9-in-1-foldable-knife-multifunctional-pliers",
        permalink: "https://shippr.store/product/9-in-1-foldable-knife-multifunctional-pliers/",
        date_created: "2021-11-13T08:05:40",
        date_created_gmt: "2021-11-13T08:05:40",
        date_modified: "2021-11-13T15:50:00",
        date_modified_gmt: "2021-11-13T15:50:00",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of 9 in 1 Foldable Knife Multifunctional Pliers<br />\nFunctions: Folding pliers, scissors, small slotted screwdriver, bottle opener, serrated knife, awl, cross screwdriver, knife and saw<br />\n10 screwdriver bits, including Torx screwdriver bits, flathead screwdriver bits, cross screwdriver bits, socket wrench bits<br />\nWith harden steel, very durable to use<br />\nWith a nylon sheath for carrying the too<br />\nType: Multitools<br />\nFor:Adventure,Camping,Climbing,Collecting,Cycling,Daily Use,Hiking,Home use,Motorcycle,Mountaineering,Other Outdoor Activities,Travel<br />\nWeight Range:201g-500g<br />\nMaterial: Stainless Steel<br />\nUnfold Length:16.5 cm<br />\nFold Length:10.4 cm<br />\nColor: Black<br />\nPackage weight:0.407 kg<br />\nPocket Survival Multifunctional Plier is made of high quality stainless steel, durable, non-slip handle, feel comfortable,<br />\nBelt Pouch packing, hard shell interior to protect for tool for years to come, cover flap with heavy duty snap.<br />\nCompact folding design features non-slip handles and spring-loaded functionality to reduce hand fatigue.<br />\nThis product is a super outdoor camping tools, pliers have specific utility functions, home daily, outdoor camping, you can make handy.</p>\n",
        short_description: "",
        sku: "XBEPAPA798",
        price: "999",
        regular_price: "1999",
        sale_price: "999",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: true,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 58,
                name: "Home",
                slug: "home",
            },
            {
                id: 60,
                name: "Kitchen",
                slug: "kitchen",
            },
        ],
        tags: [],
        images: [
            {
                id: 1989,
                date_created: "2021-11-13T08:05:40",
                date_created_gmt: "2021-11-13T08:05:40",
                date_modified: "2021-11-13T08:05:40",
                date_modified_gmt: "2021-11-13T08:05:40",
                src: "https://shippr.store/wp-content/uploads/2021/11/b304752e95be9f65425af55898d19a4b.jpg_1000x1000q90.jpg",
                name: "b304752e95be9f65425af55898d19a4b.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>1,999.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>999.00</bdi></span></ins>',
        related_ids: [1980, 1978],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1990",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1988,
        name: "Luxury Type Fashionable Round Shape Magnetive Chain Buckle Blue Colour Watch For Women",
        slug: "luxury-type-fashionable-round-shape-magnetive-chain-buckle-blue-colour-watch-for-women",
        permalink: "https://shippr.store/product/luxury-type-fashionable-round-shape-magnetive-chain-buckle-blue-colour-watch-for-women/",
        date_created: "2021-11-13T08:05:37",
        date_created_gmt: "2021-11-13T08:05:37",
        date_modified: "2021-11-13T15:50:22",
        date_modified_gmt: "2021-11-13T15:50:22",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of Luxury Type Fashionable Round Shape Magnetive Chain Buckle Blue Colour Watch For Women<br />\nMovement: Quartz<br />\nDial : Analog<br />\nMaterial: Stainless Steels<br />\nShape : RoundDial<br />\nStrap : Metal Chain<br />\nDial Sixe : 30mm<br />\nCase Diameter: 7mm<br />\nMagnetive Buckle<br />\nChain Length: 21 cm<br />\nNew Fashionable Atractive Midel<br />\nFor Women & Girl</p>\n",
        short_description: "",
        sku: "XBEPAPA797",
        price: "599",
        regular_price: "999",
        sale_price: "599",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: true,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 34,
                name: "Fit Bands",
                slug: "fit-bands",
            },
            {
                id: 33,
                name: "Smartwatch",
                slug: "smartwatch",
            },
            {
                id: 32,
                name: "Wearables",
                slug: "wearables",
            },
        ],
        tags: [],
        images: [
            {
                id: 1987,
                date_created: "2021-11-13T08:05:37",
                date_created_gmt: "2021-11-13T08:05:37",
                date_modified: "2021-11-13T08:05:37",
                date_modified_gmt: "2021-11-13T08:05:37",
                src: "https://shippr.store/wp-content/uploads/2021/11/295dafe68936b6f7aa1e21523dbc844f.jpg_1000x1000q90.jpg",
                name: "295dafe68936b6f7aa1e21523dbc844f.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>999.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>599.00</bdi></span></ins>',
        related_ids: [1976, 1984, 1986],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1988",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1986,
        name: "Smart Bracelet- Band Smart Wristband Bracelet Watch",
        slug: "smart-bracelet-band-smart-wristband-bracelet-watch",
        permalink: "https://shippr.store/product/smart-bracelet-band-smart-wristband-bracelet-watch/",
        date_created: "2021-11-13T08:05:35",
        date_created_gmt: "2021-11-13T08:05:35",
        date_modified: "2021-11-13T15:50:36",
        date_modified_gmt: "2021-11-13T15:50:36",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of Smart Bracelet- Band Smart Wristband Bracelet Watch<br />\nMaterial: Silicone tape + PC case<br />\nCharging: USB Contact charging<br />\nScreen size: 0.66 inches<br />\nBattery: 80mAh<br />\nBracelet size: 50mm * 24mm * 11.6mm<br />\nWrist strap size: 235mm * 24mm * 11.6mm<br />\nOperation: single touch<br />\nLink phone mode: Bluetooth 4.0<br />\nRecord the number of steps, calories, mileage, sleep duration, sleep depth<br />\nMeasurement of heart rate, blood pressure, blood oxygen, fatigue values<br />\nCall, SMS, QQ, WeChat, Facebook, twitter and other news alerts<br />\nAlarm clock, find the hand ring, hand-shining screen, the whole point of measurement</p>\n",
        short_description: "",
        sku: "XBEPAPA796",
        price: "1999",
        regular_price: "1999",
        sale_price: "",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: false,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 34,
                name: "Fit Bands",
                slug: "fit-bands",
            },
            {
                id: 33,
                name: "Smartwatch",
                slug: "smartwatch",
            },
            {
                id: 17,
                name: "Uncategorized",
                slug: "uncategorized",
            },
            {
                id: 32,
                name: "Wearables",
                slug: "wearables",
            },
        ],
        tags: [],
        images: [
            {
                id: 1985,
                date_created: "2021-11-13T08:05:34",
                date_created_gmt: "2021-11-13T08:05:34",
                date_modified: "2021-11-13T08:05:34",
                date_modified_gmt: "2021-11-13T08:05:34",
                src: "https://shippr.store/wp-content/uploads/2021/11/84b075e6796c58bd2149416dd47ac883.jpg_1000x1000q90.jpg",
                name: "84b075e6796c58bd2149416dd47ac883.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>1,999.00</bdi></span>',
        related_ids: [68, 84, 76, 82, 56],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1986",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1984,
        name: "Watch For Women Fashion Starry Sky Convex Glass Quartz Mesh With Magnetic Buckle Ladies Watch",
        slug: "watch-for-women-fashion-starry-sky-convex-glass-quartz-mesh-with-magnetic-buckle-ladies-watch",
        permalink:
            "https://shippr.store/product/watch-for-women-fashion-starry-sky-convex-glass-quartz-mesh-with-magnetic-buckle-ladies-watch/",
        date_created: "2021-11-13T08:05:33",
        date_created_gmt: "2021-11-13T08:05:33",
        date_modified: "2021-11-13T15:52:07",
        date_modified_gmt: "2021-11-13T15:52:07",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of Watch For Women Fashion Starry Sky Convex Glass Quartz Mesh With Magnetic Buckle Ladies Watch<br />\nThis is a good present<br />\nFashionable, very charming for all occasions<br />\nPrecise time and keep good time<br />\nHigh abrasion resistant mineral<br />\nConvenient to adjust the length and not easy to fall off<br />\nVery unique, fashion and elegant design<br />\nThe convex dial reflects the beautiful curvature through the light, showing the stylish personality<br />\nThe new magnetic strap solves the problem that your strap is too short or too long to wear inappropriately. The 27cm can be adjusted freely. The strap is strong and the suction is strong. It is the best choice for your fashion.<br />\nThe trend of the starry sky dial makes your charm bloom, luxurious and noble<br />\nVery suitable as a gift<br />\nSuitable for any occasion<br />\nEasy to match<br />\nFeature:<br />\nCase diameter:33mm<br />\nDial thickness: 11mm<br />\nStrap length:270mm (including case)<br />\nStrap material: Alloy<br />\nHead material: Alloy<br />\nPackage Content:<br />\n1X Watch</p>\n",
        short_description: "",
        sku: "XBEPAPA795",
        price: "499",
        regular_price: "1299",
        sale_price: "499",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: true,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 62,
                name: "Analog Watch",
                slug: "analog-watch",
            },
            {
                id: 17,
                name: "Uncategorized",
                slug: "uncategorized",
            },
            {
                id: 32,
                name: "Wearables",
                slug: "wearables",
            },
        ],
        tags: [],
        images: [
            {
                id: 1983,
                date_created: "2021-11-13T08:05:33",
                date_created_gmt: "2021-11-13T08:05:33",
                date_modified: "2021-11-13T08:05:33",
                date_modified_gmt: "2021-11-13T08:05:33",
                src: "https://shippr.store/wp-content/uploads/2021/11/3ff62ee781a27bd946bea092c31fef03.jpg_1000x1000q90.jpg",
                name: "3ff62ee781a27bd946bea092c31fef03.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>1,299.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>499.00</bdi></span></ins>',
        related_ids: [88, 78, 76, 53, 60],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1984",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1982,
        name: "9.66'' HD 1080P Screen Night vision Camera Dual Lens Dash Cam Video Recorder",
        slug: "9-66-hd-1080p-screen-night-vision-camera-dual-lens-dash-cam-video-recorder",
        permalink: "https://shippr.store/product/9-66-hd-1080p-screen-night-vision-camera-dual-lens-dash-cam-video-recorder/",
        date_created: "2021-11-13T08:05:30",
        date_created_gmt: "2021-11-13T08:05:30",
        date_modified: "2021-11-13T08:05:30",
        date_modified_gmt: "2021-11-13T08:05:30",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of 9.66'' HD 1080P Screen Night vision Camera Dual Lens Dash Cam Video Recorder<br />\nFEATURES-<br />\n-9.66 inch IPS HD touch screen, true full HD 1080p;<br />\n- Front 170Â° wide angle, with a high-definition screen to give you a clear experience;<br />\n- Lingtong 6248 solution, cost-effective and high reliability 1080p solution;<br />\n- New design, suitable screen size, loved by customers;<br />\n- Parking monitoring, motion detection, gravity sensing, emergency locking, multiple protections guard your car;<br />\n- Support 720P streaming media rear view camera, with starlight night vision function, 140Â° wide angle;<br />\n- Zinc alloy casing with 2.5D glass for wide lens angle;</p>\n",
        short_description: "",
        sku: "XBEPAPA794",
        price: "8999",
        regular_price: "9999",
        sale_price: "8999",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: true,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 17,
                name: "Uncategorized",
                slug: "uncategorized",
            },
        ],
        tags: [],
        images: [
            {
                id: 1981,
                date_created: "2021-11-13T08:05:30",
                date_created_gmt: "2021-11-13T08:05:30",
                date_modified: "2021-11-13T08:05:30",
                date_modified_gmt: "2021-11-13T08:05:30",
                src: "https://shippr.store/wp-content/uploads/2021/11/a9d973a47b5a9ed49c96fef2fbf275d5.jpg_1000x1000q90.jpg",
                name: "a9d973a47b5a9ed49c96fef2fbf275d5.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>9,999.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>8,999.00</bdi></span></ins>',
        related_ids: [66, 68, 62, 51, 80],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1982",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1980,
        name: "Charcoal Base Portable Folding Space Saver Barbeque Grill Toaster,Black",
        slug: "charcoal-base-portable-folding-space-saver-barbeque-grill-toasterblack",
        permalink: "https://shippr.store/product/charcoal-base-portable-folding-space-saver-barbeque-grill-toasterblack/",
        date_created: "2021-11-13T08:05:28",
        date_created_gmt: "2021-11-13T08:05:28",
        date_modified: "2021-11-13T15:52:46",
        date_modified_gmt: "2021-11-13T15:52:46",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of Charcoal Base Portable Folding Space Saver Barbeque Grill Toaster,Black<br />\n1.Model: A913<br />\n2.Product name: Portable Folding Barbecue<br />\n3.Size: 27cm X 30cm X 29cm<br />\n4.Color: Black<br />\n5.Product Type: Charcoal grill<br />\n6.Installation Location: Portable<br />\n7.Material: stainless steel<br />\n8.Fuel Type: Charcoal<br />\n9.Compact and easy to assemble,Slim line design<br />\n10.Scope of application:Garden,Outdoor ,Camping,Cooking</p>\n",
        short_description: "",
        sku: "XBEPAPA793",
        price: "1190",
        regular_price: "1599",
        sale_price: "1190",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: true,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 58,
                name: "Home",
                slug: "home",
            },
            {
                id: 60,
                name: "Kitchen",
                slug: "kitchen",
            },
            {
                id: 17,
                name: "Uncategorized",
                slug: "uncategorized",
            },
        ],
        tags: [],
        images: [
            {
                id: 1979,
                date_created: "2021-11-13T08:05:27",
                date_created_gmt: "2021-11-13T08:05:27",
                date_modified: "2021-11-13T08:05:27",
                date_modified_gmt: "2021-11-13T08:05:27",
                src: "https://shippr.store/wp-content/uploads/2021/11/efce8ac4745688b69f7c96402b3af437.jpg_1000x1000q90.jpg",
                name: "efce8ac4745688b69f7c96402b3af437.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>1,599.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>1,190.00</bdi></span></ins>',
        related_ids: [98, 53, 90, 78, 80],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1980",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1978,
        name: "Deerma F329 Air Humidifier - Transparent Water Tank Black Air Humidifier",
        slug: "deerma-f329-air-humidifier-transparent-water-tank-black-air-humidifier",
        permalink: "https://shippr.store/product/deerma-f329-air-humidifier-transparent-water-tank-black-air-humidifier/",
        date_created: "2021-11-13T08:05:25",
        date_created_gmt: "2021-11-13T08:05:25",
        date_modified: "2021-11-13T15:53:44",
        date_modified_gmt: "2021-11-13T15:53:44",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of Deerma F329 Air Humidifier - Transparent Water Tank Black Air Humidifier<br />\nðŸ”¥Features:-Transparent water tank design-Ultrasonic welding process-<br />\n5L huge capacity water tank-Water mist distribution system-<br />\nPurifying dust filter cotton-Water shortage protection reminder-<br />\n36dB light operationðŸ“˜<br />\nParameters:Product model: DEM-F329Voltage: 220V-50HzPower: 25W Color: WhiteCapacity:<br />\n5LMachine size: 220*220*285mmðŸ“¦Package Contents:1 Ã— Humidifier1 Ã— Instruction Manual1 Ã— Certificate of Conformity1 Ã— Silver lon Ag<br />\n.</p>\n",
        short_description: "",
        sku: "XBEPAPA792",
        price: "5999",
        regular_price: "5999",
        sale_price: "",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: false,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 58,
                name: "Home",
                slug: "home",
            },
            {
                id: 63,
                name: "Others",
                slug: "home-others",
            },
            {
                id: 17,
                name: "Uncategorized",
                slug: "uncategorized",
            },
        ],
        tags: [],
        images: [
            {
                id: 1977,
                date_created: "2021-11-13T08:05:25",
                date_created_gmt: "2021-11-13T08:05:25",
                date_modified: "2021-11-13T08:05:25",
                date_modified_gmt: "2021-11-13T08:05:25",
                src: "https://shippr.store/wp-content/uploads/2021/11/4611f92c488c01a2f79cae254d668946.jpg_1000x1000q90.jpg",
                name: "4611f92c488c01a2f79cae254d668946.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>5,999.00</bdi></span>',
        related_ids: [70, 82, 74, 92, 88],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1978",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1976,
        name: "Fashionable Blue Colour Magnetive Chain Round Shape Watch For Women",
        slug: "fashionable-blue-colour-magnetive-chain-round-shape-watch-for-women",
        permalink: "https://shippr.store/product/fashionable-blue-colour-magnetive-chain-round-shape-watch-for-women/",
        date_created: "2021-11-13T08:05:23",
        date_created_gmt: "2021-11-13T08:05:23",
        date_modified: "2021-11-13T15:54:05",
        date_modified_gmt: "2021-11-13T15:54:05",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of Fashionable Blue Colour Magnetive Chain Round Shape Watch For Women<br />\nMovement: Quartz<br />\nDial : Analog<br />\nMaterial: Stainless Steels<br />\nShape : RoundDial<br />\nStrap : Metal Chain<br />\nDial Sixe : 30mm<br />\nCase Diameter: 7mm<br />\nMagnetive Buckle<br />\nChain Length: 21 cm<br />\nNew Fashionable Atractive Midel<br />\nFor Women & Girl</p>\n",
        short_description: "",
        sku: "XBEPAPA791",
        price: "599",
        regular_price: "999",
        sale_price: "599",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: true,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 62,
                name: "Analog Watch",
                slug: "analog-watch",
            },
            {
                id: 32,
                name: "Wearables",
                slug: "wearables",
            },
        ],
        tags: [],
        images: [
            {
                id: 1975,
                date_created: "2021-11-13T08:05:23",
                date_created_gmt: "2021-11-13T08:05:23",
                date_modified: "2021-11-13T08:05:23",
                date_modified_gmt: "2021-11-13T08:05:23",
                src: "https://shippr.store/wp-content/uploads/2021/11/ece335e7d0612a5fbec72349e7bb168c.jpg_1000x1000q90.jpg",
                name: "ece335e7d0612a5fbec72349e7bb168c.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>999.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>599.00</bdi></span></ins>',
        related_ids: [1986, 1984, 1988],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1976",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1974,
        name: "Wired Game Controller For Xbox 360",
        slug: "wired-game-controller-for-xbox-360",
        permalink: "https://shippr.store/product/wired-game-controller-for-xbox-360/",
        date_created: "2021-11-13T08:05:21",
        date_created_gmt: "2021-11-13T08:05:21",
        date_modified: "2021-11-13T15:54:56",
        date_modified_gmt: "2021-11-13T15:54:56",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of Wired Game Controller For Xbox 360<br />\nThe Xbox 360 Controller features an extended nine-foot cable and a comfortable ergonomic design.<br />\nThe centralized, glowing Xbox Guide Button grants you quick access to your digital movie, music, and games libraries.<br />\nThe ultimate in gamer flexibility, precision, control, quality, and comfort are all yours.<br />\nThe Xbox 360 Controller features an extended nine-foot cable and a comfortable ergonomic design, centralized, glowing Xbox Guide Button grants you quick access to your digital movie, music, and games libraries, ultimate in gamer flexibility, precision, control, quality, and comfort are all yours.</p>\n",
        short_description: "",
        sku: "XBEPAPA790",
        price: "2199",
        regular_price: "2199",
        sale_price: "",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: false,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 64,
                name: "Game Contollers",
                slug: "game-contollers",
            },
            {
                id: 46,
                name: "Gaming",
                slug: "gaming",
            },
            {
                id: 17,
                name: "Uncategorized",
                slug: "uncategorized",
            },
        ],
        tags: [],
        images: [
            {
                id: 1973,
                date_created: "2021-11-13T08:05:20",
                date_created_gmt: "2021-11-13T08:05:20",
                date_modified: "2021-11-13T08:05:20",
                date_modified_gmt: "2021-11-13T08:05:20",
                src: "https://shippr.store/wp-content/uploads/2021/11/435d5e900e335262fc5d830bbb537f5b.jpg_1000x1000q90.jpg",
                name: "435d5e900e335262fc5d830bbb537f5b.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>2,199.00</bdi></span>',
        related_ids: [96, 84, 98, 53, 68],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1974",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
    {
        id: 1972,
        name: "Remote Control Camera Drone Foldable Quadcopter-Black",
        slug: "remote-control-camera-drone-foldable-quadcopter-black",
        permalink: "https://shippr.store/product/remote-control-camera-drone-foldable-quadcopter-black/",
        date_created: "2021-11-13T08:05:19",
        date_created_gmt: "2021-11-13T08:05:19",
        date_modified: "2021-11-13T08:05:19",
        date_modified_gmt: "2021-11-13T08:05:19",
        type: "simple",
        status: "publish",
        featured: false,
        catalog_visibility: "visible",
        description:
            "<p>Product details of Remote Control Camera Drone Foldable Quadcopter-Black<br />\nController: 2.4GHz mode<br />\nChannels: 4 Channels<br />\nGyroscope: 6-Axis<br />\nPixels:2MP=720PHD<br />\nControl distance: Control by phone about 50m, Control by controller about 100m<br />\nBattery for quadcopter: 3.7V 900mAh li-po battery<br />\nCharging time: About 90 minutes<br />\nWorking time: About 10-15minutes<br />\nBattery for remote controller: AA battery (not included)<br />\nFunction: Track Flight/360-degree Rolling Over/Headless Mode/LED Lights/One Key<br />\nAutomatic Return/Altitude Hold/FPV/VR/Mode/Gravity sensing mode/Speed Mode/A key to take off and landThe foldable drone can not only equiped with a controller, but also it can be controlled by phone app. you just need to download a right app from the instruction book.and open the phone wifi to find it and connect it.you can take photos and videos, and flies the drone by the phone.FPV Real-Time Transmissionï¼šEquipped with 2MP Cameras and Control your drone with App wifi connection to your phone (ios or android). Bring a new perspective to your photos and videos from the air. Images and videos will be listed in both App and mobile album system.Signal connection of the rc drone with the controller: open the switches of drone and controller, push the throttle stick (the left stick) up and down one time, the lights on the drone and controller will stop flashing.3D Flips Roll & One-key Return:The latest 6-axis flight control system stability.One key to roll for 360Â° flip with LED makes night flying a better and more fun experience. Built-in position system and gravity sensor, memorize previous position, simply click a button to drive the drone back.Some issue might be met for all kinds of the drone:<br />\nif the app can not connect with the drone, please re-download it and reset the drone, then connect them again.<br />\nif the camera canâ€™t work, please check your phone permissions, as sometime your phone canâ€™t allows the app open the camera.<br />\nplease notes the droneâ€™s flying distance, donâ€™t fly it exceed the biggest distance, otherwise, it will fly away and the signal will lost too.<br />\nplease fly it at a big and wide place, away from the tree, water and fire.<br />\nDon't push the throttle up hard directly. Adjust the throttle slowly to avoid damage caused by loss of control.<br />\nThis FPV quadcopter only fit for age above 14+ experienced users. Before assemble the drone, please read the user manual first to know the assembling procedure and how to operate it.</p>\n",
        short_description: "",
        sku: "XBEPAPA789",
        price: "7999",
        regular_price: "10000",
        sale_price: "7999",
        date_on_sale_from: null,
        date_on_sale_from_gmt: null,
        date_on_sale_to: null,
        date_on_sale_to_gmt: null,
        on_sale: true,
        purchasable: true,
        total_sales: 0,
        virtual: false,
        downloadable: false,
        downloads: [],
        download_limit: -1,
        download_expiry: -1,
        external_url: "",
        button_text: "",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: false,
        stock_quantity: null,
        backorders: "no",
        backorders_allowed: false,
        backordered: false,
        low_stock_amount: null,
        sold_individually: false,
        weight: "",
        dimensions: {
            length: "",
            width: "",
            height: "",
        },
        shipping_required: true,
        shipping_taxable: true,
        shipping_class: "",
        shipping_class_id: 0,
        reviews_allowed: true,
        average_rating: "0.00",
        rating_count: 0,
        upsell_ids: [],
        cross_sell_ids: [],
        parent_id: 0,
        purchase_note: "",
        categories: [
            {
                id: 17,
                name: "Uncategorized",
                slug: "uncategorized",
            },
        ],
        tags: [],
        images: [
            {
                id: 1971,
                date_created: "2021-11-13T08:05:18",
                date_created_gmt: "2021-11-13T08:05:18",
                date_modified: "2021-11-13T08:05:18",
                date_modified_gmt: "2021-11-13T08:05:18",
                src: "https://shippr.store/wp-content/uploads/2021/11/0e2512ce24f2b9f20c9477b54b26acc4.jpg_1000x1000q90.jpg",
                name: "0e2512ce24f2b9f20c9477b54b26acc4.jpg_1000x1000q90.jpg",
                alt: "",
            },
        ],
        attributes: [],
        default_attributes: [],
        variations: [],
        grouped_products: [],
        menu_order: 0,
        price_html:
            '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>10,000.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#8360;</span>7,999.00</bdi></span></ins>',
        related_ids: [86, 92, 94, 62, 100],
        meta_data: [],
        stock_status: "instock",
        _links: {
            self: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products/1972",
                },
            ],
            collection: [
                {
                    href: "https://shippr.store/wp-json/wc/v3/products",
                },
            ],
        },
    },
];
